-- ============================================================
-- Seed Data — Sample Podcasts
-- Run AFTER 001_schema.sql
-- ============================================================

insert into public.podcasts (
  title, slug, short_description, description,
  country, case_types, format_type, host_style, factual_style,
  binge_factor, episode_length, episode_count,
  best_episode_to_start, platforms, quick_verdict,
  newsletter_worthy_summary, is_featured, is_published
) values
(
  'Serial',
  'serial',
  'The podcast that launched a thousand true crime shows. Season 1 re-investigates a 1999 murder with extraordinary depth.',
  'Investigative journalism podcast devoting an entire season to one true story. Season 1 re-investigates the 1999 murder of teenager Hae Min Lee and whether her convicted killer, Adnan Syed, actually committed the crime.',
  'US',
  ARRAY['Cold Case', 'Murder', 'Courtroom'],
  'Serialized',
  'Single Host',
  'Mixed',
  9, '45 min', '4 seasons',
  'S1 Ep1 — "The Alibi"',
  ARRAY['Apple Podcasts', 'Spotify', 'Pocket Casts'],
  'Must listen',
  'The podcast that launched a thousand true crime shows — Serial''s Season 1 remains the gold standard for investigative audio journalism.',
  true, true
),
(
  'Crime Junkie',
  'crime-junkie',
  'Tight, well-researched true crime in under an hour every Monday. The perfect gateway podcast.',
  'Weekly anthology podcast covering a new true crime case every Monday — cold cases, missing persons, serial killers, and stories of community members who fought for justice, always told from the victim''s perspective.',
  'US',
  ARRAY['Cold Case', 'Missing Person', 'Serial Killer', 'Murder'],
  'Episodic',
  'Dual Host',
  'Purely Factual',
  8, '30-45 min', '565+ episodes',
  '"MISSING: Kristin Smart" or "MURDERED: Hae Min Lee"',
  ARRAY['Apple Podcasts', 'Spotify', 'iHeart'],
  'Must listen',
  'Crime Junkie delivers tight, well-researched true crime in under an hour every Monday — the perfect gateway podcast for newcomers.',
  true, true
),
(
  'In the Dark',
  'in-the-dark',
  'Three-time Peabody Award winner. Investigative podcasting that holds the justice system accountable in real time.',
  'Award-winning investigative journalism podcast scrutinising not just crimes but the systemic failures of law enforcement and the justice system. Season 2 spent two years investigating Curtis Flowers, tried six times for the same murder.',
  'US',
  ARRAY['Courtroom', 'Cold Case', 'Systemic Injustice', 'Murder'],
  'Serialized',
  'Single Host',
  'Purely Factual',
  9, '45-60 min', '3 seasons',
  'Season 2 Episode 1 — "A Bar Fight"',
  ARRAY['Apple Podcasts', 'Spotify', 'NPR'],
  'Must listen',
  'Three-time Peabody Award winner In the Dark is investigative podcasting at its finest — it doesn''t just tell crime stories, it holds the justice system accountable in real time.',
  true, true
),
(
  'Bear Brook',
  'bear-brook',
  'Stephen King called it "the best true crime podcast I have ever heard." DNA genealogy cracked this case live.',
  'Four unidentified bodies found in barrels in a New Hampshire forest in 1985 — and how, decades later, the case was cracked using pioneering DNA genealogy techniques that changed forensic science forever.',
  'US',
  ARRAY['Cold Case', 'Murder', 'Forensic Science', 'Unidentified Victims'],
  'Serialized',
  'Single Host',
  'Purely Factual',
  9, '30-60 min', '2 seasons',
  'S1 Ep1 — "Two Barrels"',
  ARRAY['Apple Podcasts', 'Spotify', 'Stitcher'],
  'Must listen',
  'Bear Brook is the rare true crime podcast that advances science as it tells its story — DNA genealogy was pioneered live to crack this case, making it both gripping and genuinely historic.',
  true, true
),
(
  'Casefile True Crime',
  'casefile-true-crime',
  'The anonymous Australian host delivers fully scripted, deeply researched episodes. The gold standard for no-nonsense true crime.',
  'An anonymous Australian host delivers fully scripted, deeply researched episodes on criminal cases from around the world — with no host chatter, just the story.',
  'AU',
  ARRAY['Cold Case', 'Serial Killer', 'Murder', 'Missing Person'],
  'Episodic',
  'Single Host',
  'Purely Factual',
  9, '60-120 min', '300+ episodes',
  'Case 36 — "Amy" or Case 48 — "Jeanne Doelp"',
  ARRAY['Apple Podcasts', 'Spotify', 'Patreon'],
  'Must listen',
  'With over 600 million downloads, Casefile''s anonymous host and clinical storytelling set the gold standard for no-nonsense true crime.',
  true, true
),
(
  'Bone Valley',
  'bone-valley',
  'Named the best true crime podcast of 2022 by The New Yorker, The Atlantic, and Slate. Pulitzer-level journalism in podcast form.',
  'Nine-episode podcast by Pulitzer Prize-winning author Gilbert King investigating the wrongful conviction of Leo Schofield for the 1987 murder of his wife — a case where the real killer''s fingerprints were identified 15 years later but the justice system refused to act.',
  'US',
  ARRAY['Wrongful Conviction', 'Murder', 'Courtroom', 'Cold Case'],
  'Serialized',
  'Single Host',
  'Purely Factual',
  9, '60 min', '9 episodes',
  'Episode 1',
  ARRAY['Apple Podcasts', 'Spotify', 'Audible'],
  'Must listen',
  'Named the best true crime podcast of 2022 by The New Yorker, The Atlantic, and Slate — Bone Valley is a masterpiece that proves Pulitzer-level journalism can still come in podcast form.',
  true, true
),
(
  'West Cork',
  'west-cork',
  'One of the finest true crime podcasts ever made. A meticulous investigation into a brutal murder that divided two nations.',
  '13-episode Audible Original documentary investigating the brutal 1996 murder of French filmmaker Sophie Toscan du Plantier at her holiday home near Schull in West Cork, Ireland. Ian Bailey was the prime suspect — convicted in absentia in France but never extradited.',
  'IE',
  ARRAY['Cold Case', 'Murder', 'Unsolved'],
  'Serialized',
  'Dual Host',
  'Purely Factual',
  9, '40-60 min', '13 episodes',
  'Episode 1',
  ARRAY['Audible', 'Spotify', 'Apple Podcasts'],
  'Must listen',
  'West Cork is one of the finest true crime podcasts ever made — a meticulous, atmospheric investigation into a brutal murder that has divided a small Irish community and two nations for nearly 30 years.',
  false, true
),
(
  'Morbid',
  'morbid',
  'Apple ranked it the 10th most popular US podcast of 2024. Forensic insight with warmth — the perfect combination.',
  'True crime, creepy history, and all things spooky hosted by former autopsy technician Alaina Urquhart and her niece Ash Kelley — covering serial killers, forensic cases, paranormal stories, and historical crimes twice a week.',
  'US',
  ARRAY['Serial Killer', 'Murder', 'Cold Case', 'Historical Crime'],
  'Episodic',
  'Dual Host',
  'Mixed',
  8, '60-90 min', '875+ episodes',
  'Ep1 "The Toy Box Killer"',
  ARRAY['Apple Podcasts', 'Spotify', 'Amazon Music'],
  'Must listen',
  'Morbid combines the forensic insight of an autopsy tech with the warmth of best friends — Apple ranked it the 10th most popular US podcast of 2024 for good reason.',
  false, true
),
(
  'Swindled',
  'swindled',
  'Columbia Journalism Review called it "the funniest, most expansive podcast" in the genre. Corporate crime, devastating wit.',
  'Anonymous host "A Concerned Citizen" delivers dry, withering narrations of real-world white-collar crime — corporate fraud, environmental disasters, Ponzi schemes — with biting satire and meticulous research.',
  'US',
  ARRAY['White-Collar Crime', 'Corporate Fraud', 'Financial Crime'],
  'Episodic',
  'Single Host',
  'Mixed',
  8, '30-45 min', '300+ episodes',
  '"Lumber Liquidators" or "WellCare Health Plans"',
  ARRAY['Apple Podcasts', 'Spotify', 'RSS'],
  'Must listen',
  'Columbia Journalism Review called Swindled "the funniest, most expansive podcast" in the true crime genre — the anonymous host''s deadpan fury at corporate evil is utterly addictive.',
  false, true
),
(
  'Crimetown',
  'crimetown',
  'The New York Times compared it to The Wire. A sprawling, character-driven investigation into organised crime in Providence.',
  'Gimlet Media landmark anthology chronicling the world of organised crime in Providence, Rhode Island — from the Patriarca mob to corrupt mayor Buddy Cianci — across three decades.',
  'US',
  ARRAY['Organised Crime', 'Political Corruption', 'Murder', 'Fraud'],
  'Serialized',
  'Dual Host',
  'Mixed',
  9, '30-45 min', '2 seasons',
  'S1 Ep1 — "Welcome to Providence"',
  ARRAY['Apple Podcasts', 'Spotify', 'Gimlet'],
  'Must listen',
  'Crimetown is the closest podcasting has come to The Wire — a sprawling, character-driven investigation into one city''s organised crime that will ruin you for lesser true crime.',
  false, true
);

-- Make the first user an admin (update with real email after first signup)
-- update public.profiles set is_admin = true where email = 'admin@yourdomain.com';
